package com.guardforce.guard.ui.nav

object Routes {
    const val PHONE = "phone"
    const val OTP = "otp"
    const val CLAIM = "claim"
    const val SET_PIN = "setpin"
    const val CHANGE_PIN = "changepin"
    const val LOCK = "lock"
    const val PERMISSIONS = "permissions"
    const val REG_SELFIE = "regselfie"
    const val HOME = "home"
    const val CHECK_IN = "checkin"
    const val CHECK_OUT = "checkout"
    const val PATROLS = "patrols"
    const val PATROL = "patrol/{id}"
    const val TASKS = "tasks"
    const val TASK = "task/{id}"
    const val LEAVE = "leave"
    const val LEAVE_APPLY = "leave/apply"
    const val HISTORY = "history"
    const val PROFILE = "profile"
    const val NOTIFICATIONS = "notifications"
    const val UPDATE = "update"
    const val BLOCKED = "blocked"
    fun patrol(id: String) = "patrol/$id"
    fun task(id: String) = "task/$id"
}
