import { chromium } from "@playwright/test";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const msgs = [];
page.on("console", (m) => { if (["error","warning"].includes(m.type())) msgs.push(m.type()+": "+m.text().slice(0,300)); });
page.on("pageerror", (e) => msgs.push("pageerror: "+e.message.slice(0,300)));
await page.goto("http://localhost:3000/login");
await page.getByLabel("Email").fill("owner@sentinel.test");
await page.getByLabel("Password").fill("guardforce");
await page.getByRole("button", { name: "Sign in" }).click();
await page.waitForURL(/localhost:3000\/$/, { timeout: 60000 });
await page.waitForTimeout(2500);
console.log(msgs.join("\n") || "no console errors");
await browser.close();
